; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;上のドキュメントを読むのが一番いいのだろうけど、とりあえずここで軽く解説
;まず[PLATFORMIO]セクションで、default_envsに普段使う環境を指定しておくと、毎回環境を指定しなくて済むようになります。
;次に[env]セクションで、全ての環境に共通する設定を行います。ここでは、使用するライブラリと、ビルドフラグを指定しています。
;んでその下はテンプレートを作ってて、teensy41、teensy40、seeed_xiao_rp2040、unoの4つの環境を用意しています。
;必要に応じて、ビルドフラグを追加したり、ライブラリを追加したりしてください。
;最後にフィルターでどのプロジェクトをビルドするか決めてる.

[platformio]
; ==========================================================
; ★ここでビルド・書き込みする機体を切り替えます★
; 一番最後の数字を 1 か 2 に書き換えるだけです。
;   target_1 : 双発機 (auto_flight)
;   target_2 : オートジャイロ (Zunrocoptor)
; ==========================================================
default_envs = ${mode.target_1}


; --- モード定義（ここは触らない） ---
[mode]
target_1 = auto_flight
target_2 = Zunrocoptor


[env]
lib_deps =
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bolderflight/Bolder Flight Systems SBUS @ ^8.1.4
monitor_filters = direct
build_flags = 
    -std=c++17


; --- Teensy 4.1 用 (600MHzの怪物) ---
[template_teensy41]
platform = teensy
board = teensy41
framework = arduino
build_flags = -D USE_TEENSY

; --- Teensy 4.0 用 (600MHzの怪物) ---
[template_teensy40]
platform = teensy
board = teensy40
framework = arduino
build_flags = -D USE_TEENSY

; --- XIAO RP2040 用 ---
[template_seeed_xiao_rp2040]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2040
framework = arduino

; --- Arduino Uno 用 ---
[template_uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -D USE_UNO


; --------------------------------------------------
; ここから個別のプログラム設定
; --------------------------------------------------

; 自動飛行用 (双発機)
[env:auto_flight]
extends = template_teensy40
; src下の共通ファイルはすべて(+)ビルドするが、Zunrocoptorのファイルだけは除外(-)する
build_src_filter = +<*> -<Zunrocoptor.cpp> -<uchida.cpp> -<delta_auto.ぷろぐら

; オートジャイロ用
[env:Zunrocoptor]
extends = template_teensy41
; src下の共通ファイルはすべて(+)ビルドするが、auto_flightのファイルだけは除外(-)する
build_src_filter = +<*> -<auto_flight.cpp> -<uchida.cpp> -<delta_auto.cpp>

; オートジャイロ用
[env:uchida]
extends = template_teensy41
; src下の共通ファイルはすべて(+)ビルドするが、auto_flightのファイルだけは除外(-)する
build_src_filter = +<*> -<auto_flight.cpp> -<Zunrocoptor.cpp> -<delta_auto.cpp>

; オートジャイロ用
[env:delta_auto]
extends = template_teensy40
; src下の共通ファイルはすべて(+)ビルドするが、auto_flightのファイルだけは除外(-)する
build_src_filter = +<*> -<auto_flight.cpp> -<Zunrocoptor.cpp> -<uchida.cpp>